### ISSUE TITLE
Weird behaviour in testModel.py

### ISSUE THREAD

**Issue by jbirkesteen** [RasmusBrostroem/ConnectFourRL#20]
Agents play differently depending on whether they are opponent or agent. This effect is large enough that it affects winrates quite considerably, which is completely unexpected.
We should probably look into where this behaviour comes from.

**Comment by RasmusBrostroem** [comment]
Solved in TrainingStrategy pull request, which will come later. The error was that the opponent was trained to play as player 1, but saw the board from player -1 perspective. Fixed by multiplying the board with -1.
