### ISSUE TITLE
Save against minmax

### ISSUE THREAD

**Issue by RasmusBrostroem** [RasmusBrostroem/ConnectFourRL#24]
Need to make the train function able to take in minimax algo as the opponent and then also save the model after x episodes, as we wont have any new generations.

**Comment by RasmusBrostroem** [comment]
Actually, couldn't we just create generations, eventhough it doesn't matter, then we are sure that we save each x episodes

**Comment by jbirkesteen** [comment]
> Actually, couldn't we just create generations, eventhough it doesn't matter, then we are sure that we save each x episodes

Hmm, sounds like a simple and valid approach.
