### ISSUE TITLE
Remarks for refactoring

### ISSUE THREAD

**Issue by jbirkesteen** [RasmusBrostroem/ConnectFourRL#42]
Overview of what we need to consider for the remaining refactoring.

### Training script
Do we want to enable simultaneous training, i.e., training two agents at the same time? Otherwise, how do we "mark" which agent has to be trained?
  - Player 1 is always the one being trained (parameter updates)
  - Agents each have an attribute specifying whether they should be trained
  - Let updating be part of a training script rather than an explicit attribute/function in env or player.

### players.py
Re-think `calculate_rewards`. At this point the method is responsible for features related to documenting with Neptune. 
Ideally, we want to move away from this, such that logging is not a part of the player classes.  
_This also means that the attributes `player.probs` and `player.succes` are irrelevant for the functionality of the player class_.

Should the configuration of rewards for each player be read from some config file? Right now they're initialised from the `_init_` method of the player class.

### env.py
Consider how we make step() give rewards to the right players.
Also, for training 2 agents: How do we reward when an opponent makes an illegal move?

**Comment by RasmusBrostroem** [comment]
### players.py
Maybe having a logging function in the player class is fine, since it is only the player that has access to the probabilities anyways.
So the player can be linked to neptune and we can call the logging function to tell the player to place its probabilities and success record onto neptune

**Comment by jbirkesteen** [comment]
Functionality for loading and saving parameters of a player. See comment below on env functionality.
 - Consider how we load and save model. Should we save the whole model and then just load the parameters or should we only save the parameters and load the parameters?
 - Saving the whole model, makes the user able to use the agent for other things, and then loading then loading the parameters into our agent is all the user needs if they want to use our class

Logging: 
       1. Consider if we want to have logging reset after each episode, so we keep a list of the stats that we want to log, and then 
           delete the content of the lists when we have logged. The downside of this is that the training script needs to be careful 
           of when we log, as the lists can become very large and take up a lot of memory
        2. Another approach is to just have a single number for each stat, e.g. win/loss rate and average loss, where we update this 
            number each match, so we cant compare episodes, but this way we will only have a single number to update and not a 
            list, so this approach wouldn't take up a lot of memory.


Env: When player quits, everything should be saved in its current state. Loading should be implemented in a way


General ideology behind the framework:  
Make a note of the responsibility of each part of the project, for example with a simple drawing.

illegal_moves: If we dont allow illegal moves, what move should then be choosen, if the agent tries to take an illegal move and how should this be decided? Random = exploration? or based on the probabilities of the legal moves?
 -- Conclusion: We find the probabilities of the legal moves and use these to sample one of the legal moves based on the 
                        probabilities.

**Comment by jbirkesteen** [comment]
## heuristic agent
The old implementation of the minmax-agent chose a column at random, if it couldn't find a best solution in `max_depth`. 
We could perhaps (slightly) improve this with an algorithm according to the following heuristic:  
1. first, run minimax with `max_depth=2` as usual. If it doesn't find an optimal solution, then move to next step
1. Check if it's possible to connect 3. If so, do it
1. Check if it's possible to connect 2. If so, do it
1. Place somewhere next to opponent/on top of opponent
1. Choose column at random, preferably in the middle of the board. 

If we want to do this, I propose we implement step 2 and 3 using the ideas behind `winning_move()`.  
I don't think this would be too difficult to implement, but we should perhaps consider if it's worth it in regards to computation time.

**Comment by jbirkesteen** [comment]
All of this is  already  done or contained in other currently open issues.
