### ISSUE TITLE
Reset of agent

### ISSUE THREAD

**Issue by jbirkesteen** [RasmusBrostroem/ConnectFourRL#6]
Make sure that agent is properly reset after some specified number of episodes.

**Comment by RasmusBrostroem** [comment]
Does this issue relate to the freezing of the agent, and can therefore be closed duo to the #10 issue?

**Comment by jbirkesteen** [comment]
No, this relates to its attributes - for instance agent.probs

**Comment by RasmusBrostroem** [comment]
Closed since elements of lists are deleted when after being used
