### ISSUE TITLE
Game ends when column is filled

### ISSUE THREAD

**Issue by RasmusBrostroem** [RasmusBrostroem/ConnectFourRL#60]
Currently, the game ends when a player fills a column, since the environment thinks that it was an illegal move.

The reason for this is that the illegal move check is done after the piece has been placed, so when the column is filled (after the piece has been placed), then we check if there is any free rows in that column. As this is not the case, the environment would say that the move was illegal.

To fix this we have to check if the move suggested by the player is illegal before we place the piece, and then we have to give this knowledge to the other functions that needs this information, i.e. 'assign_rewards' and 'is_done'.

**Comment by jbirkesteen** [comment]
Merged with to main with #70.
