### ISSUE TITLE
Visualisations

### ISSUE THREAD

**Issue by jbirkesteen** [RasmusBrostroem/ConnectFourRL#7]
## Plots and visualisations
- Plot win rate of agent against its current opponent (zigzag plot?)
- Plot win rate of agent against random bot
- Store games and animate them being played
- Is it possible to play against an agent in real time?

## Old note on benchmarks
These have been moved to #10 
#### Benchmarks
Start out by playing against random bot. After some number of episodes (alternatively after some win-rate has been achieved), store a freezed version of the agent and continue training on this one.  
Continue freezing versions and letting the agent play against the new ones.

**Comment by jbirkesteen** [comment]
Updated this issue to concern only plots. See #10 for considerations on training strategy

**Comment by RasmusBrostroem** [comment]
The plots will be made with NeptuneAI and has been made already, but will be closed with TrainingStrategy pull request.
