### ISSUE TITLE
Provide game object instead of just the board to players

### ISSUE THREAD

**Issue by jbirkesteen** [RasmusBrostroem/ConnectFourRL#80]
Currently, the `select_action()` method for players take the board in matrix representation as an argument. This, however, leads to problems when we need to define the TDAgent (and, actually, also the minimax-agent, which currently re-use some code from `connectFour` to work around this).  
The following needs to be done:  
- [x] Re-write `select_action()` for all players
- [x] Re-write other methods of the Minimax-agent to rely on the definitions in `connectFour` (e.g., instead of its own `place_piece()`.
- [x] Make sure that this change in use is reflected for methods calling `select_action()` (for instance in `Env`).
- [x] Write the `remove_piece()` method (from the minimax-agent) in `connectFour`, as both minimax and TD will need this.

This change should be fine, since the methods would usually be called from `Env` which has access to both players and `connectFour`.

**Comment by RasmusBrostroem** [comment]
Two minimax agents gives error in later stages of the game in place piece. Needs to be looked at more

**Comment by jbirkesteen** [comment]
> Two minimax agents gives error in later stages of the game in place piece. Needs to be looked at more

The issue was that the initial value of the `best_score` did not depend on the `loss_reward` specified by the user, leading the player to choose column `None` when it couldn't avoid a loss. This was resolved in commit 88952cc.
