### ISSUE TITLE
Calculations on GPU

### ISSUE THREAD

**Issue by jbirkesteen** [RasmusBrostroem/ConnectFourRL#9]
Is it possible to transfer **everything** to GPU - even let the game be played on GPU?
Current implementation _seems to_ require many transfers of data to/from GPU, and with the current architecture being quite small, these transfers might not be worth the time. So, either let everything run on CPU (as we've done until now) or figure out how to reduce the number of transfers, such that we only transfer in the beginning and upon saving/freezing models.

**Comment by RasmusBrostroem** [comment]
Agree, I will keep it on the CPU for now, but maybe it is possible to run the whole environment on GPU. We would have to look into if gym has this feature, otherwise I am not sure if it would be possible.

**Comment by jbirkesteen** [comment]
A transfer of the complete game is too difficult to implement with the remaining time for the assignment.
However, when networks become large enough, it can pay off. See testruns in attached file.
[testruns.txt](https://github.com/RasmusBrostroem/ConnectFourRL/files/7698916/testruns.txt)
